Module/registration
intive/patronage21-android pull request #11
Opened 2021-04-14 13:26 UTC by bartek977

2021-04-14 15:17 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/components/CustomSpacer.kt
> +fun CustomSpacer() {
a po co taki CustomSpacer?

2021-04-14 15:17 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/components/InputText.kt
> +    val inputState = remember { mutableStateOf(0) } //-1:invalid, 0:notTouched, 1:valid
tutaj te staty dałbym np do jakiegoś enuma czy coś, wtedy mógłbyś pominąć komentarz i w każdym miejscu w kodzie by było wiadomo o jaki stan chodzi

2021-04-14 15:17 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/screens/LoginScreen.kt
> +        CustomSpacer()
zwykły spacer lepiej by było

2021-04-14 15:17 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/screens/NoCodeScreen.kt
> +        CustomSpacer()
to samo

2021-04-14 15:17 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/screens/RegistrationScreen.kt
> +        CustomSpacer()
znowu CustomSpacery

2021-04-14 15:31 UTC, bartek977 commented on registration/src/main/java/com/intive/registration/components/CustomSpacer.kt
> +fun CustomSpacer() {
żeby móc łatwo edytować wielkość wszystkich spacerów- przykładowo jak uznamy że spacer ma wynosić 12dp to zmienię tylko tutaj a nie we wszystkich screenach

2021-04-14 15:48 UTC, masslany commented on registration/src/main/java/com/intive/registration/components/CustomSpacer.kt
> +fun CustomSpacer() {
To możesz sobie zrobić jakiś pliczek Constants.kt i w nim zadeklarować rozmiar jako stałą, zamiast tworzyć dedykowany Composable.

2021-04-14 15:48 UTC, bartek977 commented on registration/src/main/java/com/intive/registration/components/InputText.kt
> +    val inputState = remember { mutableStateOf(0) } //-1:invalid, 0:notTouched, 1:valid
masz rację, w sumie na początku miałem to w zamiarze, a to miało być tylko "na chwilę"

2021-04-14 16:45 UTC, bartek977 commented on registration/src/main/java/com/intive/registration/components/CustomSpacer.kt
> +fun CustomSpacer() {
@masslany w sumie racja i ten sposób lepszy

2021-04-17 18:23 UTC, KubinkiewiczDawid requested changes
@masslany Sprawdź proszę też tego PRa, ja na telefonie może coś przeoczyłem

2021-04-17 18:23 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/components/CustomButton.kt
> +fun CustomButton(
Myśle ze nie ma sensu tworzyć takiego Composable skoro jest praktycznie taki sam jak Button

2021-04-17 18:23 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/components/TechnologiesList.kt
> +    for(item in avalaibleTechnologies) {
Tutaj bym użył LazyListy

2021-04-17 18:23 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/components/TechnologiesList.kt
> +        Column {
I z tego zrobił osobny component który bym dał jako Item tej lazy listy

2021-04-17 18:23 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/viewmodels/NoCodeViewModel.kt
> +    private val _email = MutableLiveData("")
Zamiast MutavleLiveData lepiej tutaj użyć czegos dedykowanego do Composable, bodajże MutableState<> ale to już myśle że może być tez LiveData

2021-04-17 18:49 UTC, masslany commented on registration/src/main/java/com/intive/registration/components/TechnologiesList.kt
> +    for(item in avalaibleTechnologies) {
Zastanawiam się czy dla kilku technologii to ma sens.

2021-04-17 18:49 UTC, masslany commented on registration/src/main/java/com/intive/registration/components/TechnologiesList.kt
> +        Column {
Wydzielenie tego do osobnego komponentu może być, zwiększy czytelność.

2021-04-17 18:49 UTC, masslany commented on registration/src/main/java/com/intive/registration/screens/EmailVerificationScreen.kt
> +    navController: NavController? = null,
Czy jest jakiś powód dla którego domyślnie nullujesz sobie NavController?

2021-04-17 18:49 UTC, masslany commented on registration/src/main/java/com/intive/registration/screens/EmailVerificationScreen.kt
> +        KeyboardType.Number
Jakbyś mógł przy tylu parametrach podawać też ich nazwy to zdecydowanie ułatwiło by to czytelność. Mam na myśli: 
InputText( text = code, onTextChanged = {} ...) itp.

2021-04-17 18:49 UTC, masslany commented on registration/src/main/java/com/intive/registration/viewmodels/RegistrationViewModel.kt
> +    fun validateForm(): Boolean = validateFirstName() &&
W tych funkcjach zwracających Boolean trzymałbym się konwencji zaczynania nazwy od is/has - isFirstNameValid(), isEmailValid() itp.

2021-04-17 19:17 UTC, masslany commented on registration/src/main/java/com/intive/registration/viewmodels/NoCodeViewModel.kt
> +    private val _email = MutableLiveData("")
https://developer.android.com/jetpack/compose/state#viewmodel-state
@KubinkiewiczDawid Google w swoich samplach dalej trzyma dane w LiveData w ViewModelu, nie widzę w tym nic złego.

2021-04-18 07:34 UTC, bartek977 commented on registration/src/main/java/com/intive/registration/screens/EmailVerificationScreen.kt
> +    navController: NavController? = null,
hmm w sumie teraz to nie ma, screeny, które wykorzystują navCOntroller zawsze go dostają, a te które nie otrzymują mogą nie mieć tego parametru

2021-04-18 07:45 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/components/TechnologiesList.kt
> +    for(item in avalaibleTechnologies) {
może i fakt

2021-04-18 07:45 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/viewmodels/NoCodeViewModel.kt
> +    private val _email = MutableLiveData("")
tak też napisałem :)

2021-04-18 07:46 UTC, bartek977 commented on registration/src/main/java/com/intive/registration/components/TechnologiesList.kt
> +        Column {
wydaje mi się, że jest czytelne jako, że cała lista jest wydzielona jako osobny component- TechnologiesList, chyba, że macie na myśli wydzielenie checkboxa i textu jako osobny component coś w stylu TechnologiesListItem? tylko wydaje mi się, że ktoś patrząc na pętle od razu skojarzy co to będzie?

2021-04-21 15:23 UTC, masslany commented on registration/src/main/java/com/intive/registration/viewmodels/SharedViewModel.kt
> +object RegistrationSuccessDialog {
Ta nazwa troszkę sugeruje coś innego niż jest w zawartości.

2021-04-21 16:55 UTC, jlyszczarz commented on registration/src/main/java/com/intive/registration/screens/RegistrationScreen.kt
> +        label = stringResource(R.string.github_url_hint),
Byłoby dobrze, gdyby jako hint był format odpowiedzi, bo nie wiadomo, czy wpisywać login, czy cały URL.

2021-04-21 16:55 UTC, jlyszczarz commented on registration/src/main/java/com/intive/registration/screens/RegistrationScreen.kt
> +    InputText(
Tutaj przydałoby się info, ile hasło ma mieć liter, cyfr, etc.

2021-04-21 17:41 UTC, bartek977 commented on registration/src/main/java/com/intive/registration/screens/RegistrationScreen.kt
> +    InputText(
wciąż czekam na ostateczne wymagania co do walidacji pól formularza, dlatego też nic nie wpisywałem

2021-04-23 10:42 UTC, KubinkiewiczDawid requested changes
Trzymajmy się tego State hoistingu, nie wsadzajmy w każdą Compose function viewModela jako parametr.
ViewModel powinien być zawarty tylko we fragmencie którego dotyczy, do reszty funkcji przekazujemy same metody bądź zmienne.

2021-04-23 10:42 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/screens/EmailVerificationScreen.kt
> +    viewmodel: EmailVerificationViewModel,
tutaj fajnie by było nie przekazywać całego viewModelu, tylko jakieś zmienne/metody z niego (State hoisting)

2021-04-23 10:42 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/screens/EmailVerificationScreen.kt
> +    sharedViewModel: SharedViewModel
i tutaj to samo z viewModelem

2021-04-23 10:42 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/screens/LoginScreen.kt
> +fun LoginScreen(viewmodel: LoginViewModel, navController: NavController) {
to samo z ViewModelem we wszystkich composablach w tym pliku

2021-04-23 10:42 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/screens/NoCodeScreen.kt
> +fun NoCodeScreen(viewmodel: NoCodeViewModel, navController: NavController) {
ViewModel

2021-04-23 10:42 UTC, KubinkiewiczDawid commented on registration/src/main/java/com/intive/registration/screens/RegistrationScreen.kt
> +        isValid = viewmodel::isPhoneNumberValid,
State hoisting

2021-04-23 10:42 UTC, KubinkiewiczDawid commented on registration/src/main/res/values/strings.xml
> +<resources>
tutaj pewnie niektóre Stringi można by przenieść/pobrać ze wspólnego modułu UI

2021-04-23 12:39 UTC, KubinkiewiczDawid approved these changes

2021-04-23 20:48 UTC, merged