Ip2 740
intive/patronage21-android pull request #136
Opened 2021-06-14 15:03 UTC by KubinkiewiczDawid

2021-06-14 20:41 UTC, KubinkiewiczDawid commented on calendar/src/main/java/com/intive/calendar/viewmodels/EventViewModel.kt
> +                eventLogger.log("Pomyślna edycja wydarzenia")
te Stringi wszystkie muszę przenieść do Resources

2021-06-14 20:42 UTC, KubinkiewiczDawid reviewed
Stringi muszę  przenieść do resources!

2021-06-16 12:06 UTC, jlyszczarz requested changes
Z jakiegoś powodu na twoim branchu przestało działać pobieranie grup technologicznych, wszędzie tam, gdzie jest wyświetlana lista grup technologicznych, czyli np. w Kalendarzu przy dodawaniu eventu, w Rejestracji, Grupach Technologicznych. Lista jest cachowana w Roomie, więc może coś się podziało, jak modyfikowałeś bazę danych?

2021-06-16 14:22 UTC, KubinkiewiczDawid commented
> Z jakiegoś powodu na twoim branchu przestało działać pobieranie grup technologicznych, wszędzie tam, gdzie jest wyświetlana lista grup technologicznych, czyli w Rejestracji, w Kalendarzu przy dodawaniu eventu, w spinnerach w Grupach Technologicznych, Dzienniczku i Userach. Wszędzie jest błąd albo ładuje się w nieskończoność. Lista jest cachowana w Roomie, więc może coś się podziało, jak modyfikowałeś bazę danych?

poprawione, konieczna była migracja bazy danych

2021-06-16 15:20 UTC, jlyszczarz approved these changes

2021-06-16 15:42 UTC, merged