Moduł kalendarza
intive/patronage21-android pull request #24
Opened 2021-04-18 10:41 UTC by jlyszczarz

2021-04-18 11:20 UTC, masslany requested changes

2021-04-18 11:20 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/screens/EventScreen.kt
> +            HeaderMedium(name, Modifier.padding(bottom = 4.dp))
Ta kontrolka wydaje się pokrywać z wrzuconą wcześniej przeze mnie do pakietu UI - UsersHeader. Sprawdź czy nie da się ich czasem uwspólnić jakoś.

2021-04-18 11:20 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/components/MonthViewComponents.kt
> +    val currentMonth: List<Any>? by calendarViewModel.currentMonth.observeAsState()
Jak to się stało, że to jest nullowalną listą dowolnych obiektów?

2021-04-18 11:21 UTC, masslany commented
Dodatkowo w momencie, gdy wchodzę w kalendarz i tylko tam zanika cień pod AppBarem, dasz radę zdebugować dlaczego?
![image](https://user-images.githubusercontent.com/15588183/115143645-e2514b00-a048-11eb-96f3-7ff5033080c5.png)

2021-04-18 11:23 UTC, bartek977 commented on calendar/src/main/java/com/intive/calendar/utils/Constants.kt
> +val weekDaysCalendarClass = listOf("", "Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota")
można wyextractować do strings.xml jako string array

2021-04-18 19:02 UTC, KubinkiewiczDawid requested changes

2021-04-18 19:02 UTC, KubinkiewiczDawid commented on calendar/src/main/res/values/colors.xml
> +<resources>
ten plik jest w module UI

2021-04-18 19:02 UTC, KubinkiewiczDawid commented on calendar/src/main/res/values/dimens.xml
> +<?xml version="1.0" encoding="utf-8"?>
ten plik jest w module UI

2021-04-18 19:02 UTC, KubinkiewiczDawid commented on gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-7.0-rc-1-all.zip
tutaj też nie wiem czy zmiana wersji nam nie pomiesza czegoś

2021-04-18 20:47 UTC, masslany commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.0.0-alpha12'
Sprawdziłem, psuje. @jlyszczarz abyśmy wszyscy pracowali na tej samej wersji prosiłbym abyś zaktualizowała Android Studio do Canary 14. Niestety, ale wersje gradle'a są ściślę z nią powiązane i nie możemy pracować na różnych.

2021-04-19 14:09 UTC, masslany approved these changes

2021-04-19 15:23 UTC, KubinkiewiczDawid approved these changes

2021-04-19 15:23 UTC, KubinkiewiczDawid commented on calendar/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_1_8
JavaVersion.VERSION_11?

2021-04-19 15:23 UTC, KubinkiewiczDawid commented on calendar/src/main/java/com/intive/calendar/components/InputText.kt
> +fun InputText(textState: String, addEventViewModel: AddEventViewModel) {
myślę że tak może zostać, ale i tak lepiej by było jakbyś przesunęła logikę na samą górę (przynajmniej przy takich funkcjach które można wydzielić jako wspólne, ta jest typowo Twoja więc może to być nie potrzebne).
Czyli zrobiła coś takiego:
![image](https://user-images.githubusercontent.com/26146436/115260476-11dc8200-a133-11eb-9bf3-c0bb39d6a0e2.png)
i dopiero tam gdzie będziesz ten InputText wywoływać podała setInputValue = viewModel::setInputValue (viewModel podawać najlepiej na samej górze (np już w samym fragmencie).
To się oczywiście tyczy wszystkich miejsc gdzie podajesz viewModel jako parametr funkcji.

2021-04-19 16:01 UTC, merged