Users/ip2 154
intive/patronage21-android pull request #30
Opened 2021-04-20 20:01 UTC by KubinkiewiczDawid

1. Pola tekstowe nie mają maksymalnej długości
2. W polach tekstowych enter przechodzi do nowej linii
5. W ekranie edycji przycisk Anuluj nie cofa do szczegółów
6. W ekranie edycji pole Numer telefonu dopuszcza litery
7. W ekranie edycji pola Imię i Nazwisko dopuszczają cyfry

2021-04-23 12:46 UTC, masslany requested changes

2021-04-23 12:46 UTC, masslany commented on users/src/main/java/com/intive/users/presentation/composables/screens/EditUserScreen.kt
> +                ) {
Wydaję mi się, że czytelniej by to wydzielić do osobnej funkcji.

2021-04-23 12:46 UTC, masslany commented on users/src/main/java/com/intive/users/presentation/composables/screens/EditUserScreen.kt
> +                ) {
Tutaj też, szczególnie, że kod ci się duplikuje.

2021-04-23 13:03 UTC, KubinkiewiczDawid commented on users/src/main/java/com/intive/users/presentation/composables/screens/EditUserScreen.kt
> +                ) {
Racja racja, nie ogarnalem

2021-04-24 08:10 UTC, jlyszczarz commented on users/src/main/java/com/intive/users/presentation/composables/screens/EditUserScreen.kt
> +                    it.all { char -> char.isLetter() }
Trzeba by też pozwolić wpisać myślnik, ktoś może mieć dwuczłonowe nazwisko.

2021-04-24 08:15 UTC, jlyszczarz commented on users/src/main/java/com/intive/users/presentation/composables/ImageEdit.kt
> +                contentDescription = null,
Ten contentDescription trzeba by wypełnić.

2021-04-24 08:30 UTC, jlyszczarz commented on users/src/main/java/com/intive/users/presentation/edit_user/EditUserFragment.kt
> +    @ExperimentalComposeUiApi
Chyba nie Ty to robiłeś, ale czy nie lepiej byłoby to Column przenieść stąd do EditUserScreen? O ile w ogóle jest potrzebne, bo wydaje mi się, że nie robi żadnej różnicy.

2021-04-29 11:43 UTC, KubinkiewiczDawid commented on users/src/main/java/com/intive/users/presentation/composables/screens/EditUserScreen.kt
> +                    it.all { char -> char.isLetter() }
racja, usuwam walidacje tekstu całkowicie:
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

2021-04-29 11:50 UTC, masslany approved these changes

2021-04-29 13:19 UTC, merged