[IP2-365] Dodanie nowego eventu
intive/patronage21-android pull request #41
Opened 2021-04-28 20:10 UTC by jlyszczarz

2021-04-28 20:33 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/viewmodels/AddEventViewModel.kt
> +        }
Wyświetlaniem Snackbara, jakkolwiek by to nie było wygodne, nie powinien zajmować się z całą pewnością ViewModel. Dodatkowo takie przeysyłanie widoku do niego może powodować w niektórych przypadkach wycieki pamięci. Jako sposób rozwiązania tego możesz wykorzystać kotlinowy Channel: https://www.youtube.com/watch?v=6v8iJDJdtMc tu prosty tutorial dla zobrazowania idei.

2021-04-28 20:33 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/viewmodels/AddEventViewModel.kt
> +        }
To samo co wyżej.

2021-04-28 20:35 UTC, bartek977 commented on calendar/src/main/java/com/intive/calendar/viewmodels/AddEventViewModel.kt
> +            _checkboxQA.value == true -> groupsList += context.getString(R.string.qa_label)
grupy technologiczne lepiej pobrać z api, bo teraz np są 4, ale za jakiś czas mogą chcieć dołączyć embedded albo coś jeszcze, ja to zrobiłem tak, że pobieram grupy i wrzucam listę do composowej petli z checkboxem i tam w oncliku daje żeby mi dodawało do listy we viewmodelu

2021-04-28 20:35 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/viewmodels/AddEventViewModel.kt
> +        return groupsList
Prędzej czy później to będzie trzeba uzależnić od grup pobieranych z API, aby w przyszłych edycjach Patronage'a, w przypadku startu innych grup, ta część wciąż działała.

2021-04-28 20:36 UTC, bartek977 commented on calendar/src/main/res/values/strings.xml
> +    <string name="mobile_label">Android</string>
i te stringi będą zbędne

2021-04-28 20:37 UTC, bartek977 commented on calendar/src/main/res/values/strings.xml
>      <string name="spinner_component_btn_desc">Right button</string>
Robimy dodatkowo angielską wersję? :P

2021-04-28 20:39 UTC, bartek977 commented on repository/src/main/java/com/intive/repository/RepositoryImpl.kt
> +        return networkRepository.addNewEvent(newEventMapper.mapFromDomainModel(event))
wydaje mi się że dobrze byłoby sprawdzić czy rzeczywiście udało się dodać event, dlatego też ta funkcja powinna zwracać odpowiedź serwera

2021-05-03 08:22 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/fragments/AddEventFragment.kt
> +    @InternalCoroutinesApi
Nie wiem czemu użyłaś tej adnotacji tutaj, ale z cała pewnością nie powinnaś. https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-internal-coroutines-api/

2021-05-03 08:31 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/screens/AddEventScreen.kt
> +                        view = view,
Teraz przekazywanie widoku jest już niepotrzebne.

2021-05-03 08:32 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/utils/IsOnlineUtil.kt
> +}
Ta klasa w ogóle ci działała? Gdy wszedłem w nią, to 11 linijka krzyczała o braku uprawnienia do czegoś w manifeście i faktycznie tego uprawnienia brakowało.

2021-05-03 09:50 UTC, jlyszczarz commented on calendar/src/main/java/com/intive/calendar/utils/IsOnlineUtil.kt
> +}
Działała wcześniej, musiało to uprawnienie zniknąć przy mergowaniu developa.

2021-05-05 17:29 UTC, masslany requested changes

2021-05-05 17:29 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/viewmodels/AddEventViewModel.kt
> +            withContext(Dispatchers.IO) {
Dobrym wzorcem wg Googla jest przekazywanie Dispatcherów przez ViewModel. Provider jest umieszczony w repozytorium, a przykład znajdziesz w moim module. Idea takiego rozwiązania jest taka, że przy testowaniu można je sobie podmienić na bardziej deterministyczne.

2021-05-05 17:29 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/viewmodels/AddEventViewModel.kt
> +    private fun validateInput(): Boolean {
Już u kogoś to wspominałem, dla funkcji zwracających Boolean nazewnictwo isTimeValid, isDateValid itp. jest zdecydowanie czytelniejsze.

2021-05-05 17:31 UTC, bartek977 commented on calendar/src/main/java/com/intive/calendar/screens/AddEventScreen.kt
> +                }
widzę, że mamy to samo do pokazania- listę technologi z checkboxami, to możemy pomyśleć, żeby wrzucić to do wspólnego ui, tylko zastanawiam się czy potrzebna jest lazyLista, czy wystarczy zwykła pętla, bo ja mam na pętli ale nie wiadomo ile tych technologii finalnie będzie, jeżeli będzie ich kilka jak dotychczas to chyba lepiej będzie na pętli

2021-05-05 17:34 UTC, masslany commented on calendar/src/main/java/com/intive/calendar/screens/AddEventScreen.kt
> +                }
W mojej subiektywnej opinii dla <10 elementów, zwykła kolumna z pętlą wystarczy. Narzut wydajnościowy w takim wypadku powinien być żaden.

2021-05-05 17:38 UTC, bartek977 reviewed
brakuje mi możliwości scrollowania całego ekranu- u mnie jest teraz tak, że widzę np wydarzenia ale mogę je scrollować tylko w ich polu co powoduje że ciągle widzę tytuł i opis a mało miejsca jest na te wydarzenia

2021-05-05 20:52 UTC, masslany approved these changes

2021-05-06 08:30 UTC, bartek977 approved these changes

2021-05-06 09:51 UTC, merged