Ip2 141
intive/patronage21-android pull request #70
Opened 2021-05-13 08:25 UTC by KubinkiewiczDawid

2021-05-13 08:37 UTC, masslany approved these changes

2021-05-13 10:17 UTC, jlyszczarz commented on tech_groups/src/main/java/com/intive/tech_groups/presentation/Stage.kt
> +data class Stage(
Czy Stage mógłby mieć jeszcze ID? Będzie mi potem potrzebne, żeby pobrać z API szczegóły etapu.

2021-05-13 10:31 UTC, jlyszczarz requested changes

2021-05-13 10:31 UTC, jlyszczarz commented on tech_groups/src/main/java/com/intive/tech_groups/presentation/Stage.kt
> +data class Stage(
Czy Stage mógłby mieć jeszcze ID? Będzie mi potem potrzebne, żeby pobrać z API szczegóły etapu.

2021-05-16 12:55 UTC, jlyszczarz approved these changes

2021-05-16 14:18 UTC, merged