Znikający layout przy nawigacji po aktywowaniu compose'owage TextField
intive/patronage21-android pull request #8
Opened 2021-04-06 18:24 UTC by masslany

Zajmowałem się naprawą buga, w którym po aktywowaniu kontrolki TextField i próbie przejścia na inny ekran nie pojawia się layout. Problem tkwi w trzymaniu NavHostFragmentu w compose'owym AndroidViewBinding, które to nawet wg Googla fragmentów hostować nie powinno.

2021-04-06 18:44 UTC, KubinkiewiczDawid commented on app/src/main/res/layout/content_main.xml
> +        app:layout_constraintTop_toTopOf="parent"
@masslany  a tutaj jakby dać:
app:layout_constraintTop_toTopOf="id/compose_view"
?

2021-04-06 20:14 UTC, masslany commented on app/src/main/res/layout/content_main.xml
> +        app:layout_constraintTop_toTopOf="parent"
Nie przejdzie. Dłuższe wyjaśnienie:
We wcześniejszej wersji trzymaliśmy AppBar i Content w Scaffoldzie. Ten odpowiada za dodanie cienia do AppBara, tak zwanej w Compose elewacji. Uwolnienie NavHostFragmentu z AndroidViewBinding powoduje, że nie można go już osadzić w Scaffoldzie i trzeba ten cień stworzyć samemu. Tutal pomysł jest taki, aby przy wykorzystaniu Surface nadać elewację dla AppBara i umieścić go w XMLu. Aby jednak ten cień był widoczny ComposeView trzymający AppBar musi być większy niż wrap_content - metodą prób i błędów ustawiłem 120dp. 
Następnie umieszczam NavHostFragment kotwicząc go do samej góry ekranu i robię margines, również ustalony metodą prób i błędów, aby jego content zaczynał się bezpośrednio pod AppBarem a jednocześnie cień AppBara na niego nachodził. 
![image](https://user-images.githubusercontent.com/15588183/113772724-5e809000-9725-11eb-8579-1b0a0b62ab17.png)

2021-04-07 09:53 UTC, sylwester-zielinski-intive requested changes

2021-04-07 09:53 UTC, sylwester-zielinski-intive commented on app/src/main/res/layout/content_main.xml
> +    android:layout_width="match_parent"
Spróbuj dodać 
android:clipChildren="false"
android:clipToPadding="false"
Dzięki temu cień ComposeView będzie mógł się narysować poza granicami ComposeView.

2021-04-07 09:53 UTC, sylwester-zielinski-intive commented on app/src/main/res/layout/content_main.xml
> +        android:layout_height="120dp"
tu wrap_content

2021-04-07 09:53 UTC, sylwester-zielinski-intive commented on app/src/main/res/layout/content_main.xml
> +        android:layout_marginTop="56dp"
to wyrzucić

2021-04-07 09:53 UTC, sylwester-zielinski-intive commented on app/src/main/res/layout/content_main.xml
> +        app:layout_constraintTop_toTopOf="parent"
tutaj Top_toBottomOf="@+id/compose_view"

2021-04-07 09:53 UTC, sylwester-zielinski-intive commented on app/src/main/res/layout/content_main.xml
> +        app:layout_constraintTop_toTopOf="parent"
Chyba rozumiem o co chodzi, ale te 120 dp trochę mi nie leży, bo jest to wartość zapisana na sztywno i jak coś zmienimy, to będzie trzeba się z tym bawić.

Zobacz, czy te rzeczy co napisałem rozwiązują Twój problem. Jeśli nie to commituj tak jak masz teraz.

2021-04-07 12:07 UTC, masslany commented on app/src/main/res/layout/content_main.xml
> +        app:layout_constraintTop_toTopOf="parent"
Wygląda na to, że to zadziałało.

2021-04-07 12:18 UTC, sylwester-zielinski-intive approved these changes

2021-04-07 12:19 UTC, merged